#-----------------------------------------------------------------------------
#  Company: Wise Monkeys
#  This script is provided "AS IS" with no warranties, and confers no rights.
#  Version 1.0
# -----------------------------------------------------------------------------
   
   # Enter Workflow name here
    name: Provisioning building block [Azure Monitor Logs]
   
    on:
      # Triggers the workflow on push request events but only for the "main" branch
      push:
        branches: [ "main" ]

    permissions:
      # Fetch an OpenID Connect (OIDC) token. This requires id-token: write
      id-token: write
      # Work with the contents of the repository. For example, contents: read permits an action to list the commits, and contents:write allows the action to create a release. 
      contents: read
    
       # This workflow contains a single job called "build-and-deploy"
    jobs:
      build-and-deploy:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
         # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
           # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout private repository
          uses: actions/checkout@v4
          with:
           # Repository name with owner. For example, actions/checkout. Default: ${{ github.repository }}
              repository: ${{ github.repository }}
           
        - name: Login to Azure
          uses: azure/login@v1
            # https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux
          with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
              #allow-no-subscriptions: true

        - name: Run Azure CLI command
          uses: azure/CLI@v1.0.8
          with:
             # Runs a set of commands using the Azure CLI shell
            inlineScript: | 
                 az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                 az stack sub create --name 'azuremonitorlogs' --location 'westeurope' --template-file './main.bicep' --parameters './param/main.bicepparam' --deny-settings-mode 'none' --yes 