    name: Provisioning log analytics Workspace
   
    on: push

    permissions:
      id-token: write
      contents: read
    
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout private repository
          uses: actions/checkout@v4
          with:
            repository: MMo001/Wise-monkeys
           

        - name: Login to Azure
          uses: azure/login@v1
          with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Run Azure CLI command
          uses: azure/CLI@v1
          with:
            inlineScript: |
                ls
                az deployment sub create  --name 'Provisioning log analytics Workspace' --location westeurope --template-file ./main.bicep --parameters ./param/main.bicepparam
    
